:Version: 4.4.0
:toc: macro
:toc-title: 目次
:toclevels: 4

= インタースティシャル（全画面）広告ガイド AMoAd SDK {version} Guide for Android

NOTE: インタースティシャル広告の概要については、link:Overview-Interstitial.asciidoc[こちら]をご参照ください。

NOTE: SDKのインストールについてはlink:Setup.asciidoc[こちら]をご参照ください。

NOTE: モジュールのダウンロードはこちら（link:https://github.com/amoad/amoad-android-sdk/releases/latest[安定版]/link:https://github.com/amoad/amoad-android-sdk/releases#[最新版]）からお願いします。

NOTE: サンプルコードが/Samples/Eclipse/AMoAdInterstitialSample/と + 
/Samples/AndroidStudio/AMoAdInterstitialSample/にありますので、管理画面から取得したsidを入力して動かしてください。

toc::[]

:numbered:
:sectnums:

== 広告を表示する

=== 実装の流れ

. 管理画面から発行されるsidを指定してモジュールを登録します。 +

	com.amoad.InterstitialAd.prepare(this, SID);

. 縦・横画面のパネル画像を設定します。 +

	com.amoad.InterstitialAd.setPortraitPanel(SID, R.drawable.amoad_panel);
	com.amoad.InterstitialAd.setLandscapePanel(SID, R.drawable.amoad_panel_l);

. 広告面をクリックできるかどうかを設定する:default = true

	com.amoad.InterstitialAd.setDisplayClickable(SID, clickable);

. 確認ダイアログを表示するかどうかを設定する:default = true

	com.amoad.InterstitialAd.setDialogShown(SID, shown);

. ボタン押下時など広告の表示を開始したいタイミングで、以下のメソッドを呼び出します。 +

	com.amoad.InterstitialAd.show(SID, new com.amoad.InterstitialAd.OnCloseListener() {
			@Override
			public void onClose(com.amoad.InterstitialAd.Result result) {
	    }
	});

. 画面回転対応のためActivityのonConfigurationChanged()をオーバーライドする。 +

	@Override
	public void onConfigurationChanged(Configuration newConfig) {
			super.onConfigurationChanged(newConfig);
			com.amoad.InterstitialAd.onConfigurationChanged(newConfig);
	}

. 画面終了時にインタースティシャル広告を閉じるためonDestroy()をオーバーライドする。 +

	@Override
	protected void onDestroy() {
			super.onDestroy();
			com.amoad.InterstitialAd.close(SID);
	}

TIP: パネル以外の画像も設定できます。以下を参照してください。
画像のサイズについては、
link:https://github.com/amoad/amoad-ios-sdk/blob/61f6e08a5a27a3390e53c8254aa60edae20f3103/Documents/Interstitial/Guide.asciidoc[こちら]をご参照ください。

=== 実装例

.MainActivity
[source,java]
----
public class MainActivity extends Activity {
	private static final String SID = "管理画面から発行されるsidを設定してください";

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		// インタースティシャル広告の準備
		com.amoad.InterstitialAd.prepare(this, SID);
		// 閉じるボタン画像（40dpx40dp）
		com.amoad.InterstitialAd.setCloseButton(SID, R.drawable.amoad_close_btn, R.drawable.amoad_close_btn_h);
		// リンクボタン画像（280dpx50dp）
		com.amoad.InterstitialAd.setLinkButton(SID, R.drawable.amoad_link_btn, R.drawable.amoad_link_btn_h);
		// 縦画面のパネル画像（310dpx380dp）
		com.amoad.InterstitialAd.setPortraitPanel(SID, R.drawable.amoad_panel);
		// 横画面のパネル画像（380dpx310dp）
		com.amoad.InterstitialAd.setLandscapePanel(SID, R.drawable.amoad_panel_l);

		// 広告面をクリックできるかどうかを設定する：デフォルトはtrue
		//com.amoad.InterstitialAd.setDisplayClickable(SID, false);
		// 確認ダイアログを表示するかどうかを設定する：デフォルトはtrue
		//com.amoad.InterstitialAd.setDialogShown(SID, false);

		findViewById(R.id.show).setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				// インタースティシャル広告を表示する
				com.amoad.InterstitialAd.show(SID, new com.amoad.InterstitialAd.OnCloseListener() {
					@Override
					public void onClose(com.amoad.InterstitialAd.Result result) {
						switch (result) {
						case Click:
							// リンクボタンがクリックされたので閉じました
							break;
						case Close:
							// 閉じるボタンがクリックされたので閉じました
							break;
						case CloseFromApp:
							// 広告のクローズ
							break;
						case Duplicated:
							// 既に開かれているので開きませんでした
							break;
						case Failure:
							// 広告の取得に失敗しました
							break;
						}
					}
				});
			}
		});
	}

	@Override
	public void onConfigurationChanged(Configuration newConfig) {
		super.onConfigurationChanged(newConfig);
		com.amoad.InterstitialAd.onConfigurationChanged(newConfig);
	}

	@Override
	protected void onDestroy() {
		super.onDestroy();
		com.amoad.InterstitialAd.close(SID);
	}
}
----

== API詳細
=== InterstitialAdクラス
==== prepare関数
管理画面から発行されるsidに紐づく広告情報を登録します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|===

==== setPortraitPanel関数
パネル画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|resId |int 2+|縦画面のパネルに使用する画像のリソースＩＤ
|===

==== setLandscapePanel関数
パネル画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|resId |int 2+|横画面のパネルに使用する画像のリソースＩＤ
|===

==== setDisplayClickable関数
広告面をクリックできるかどうかを設定する。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|clickable |boolean 2+|広告面をクリックできるかどうか(default:true)
|===

==== setDialogShown関数
確認ダイアログを表示するかどうかを設定する。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|shown |boolean 2+|確認ダイアログを表示するかどうか(default:true)
|===

==== setLinkButton関数
リンクボタン画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|resId |int 2+|リンクボタンに使用する画像のリソースＩＤ
|highlighted_resId |int 2+|リンクボタンに使用する画像（Highlight時）のリソースＩＤ
|===

==== setCloseButton関数
閉じるボタン画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|resId |int 2+|閉じるボタンに使用する画像のリソースＩＤ
|highlighted_resId |int 2+|閉じるボタンに使用する画像（Highlight時）のリソースＩＤ
|===

==== show関数
広告の表示を行います。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|===

==== close関数
広告を閉じます。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|===

TIP: リンクボタン、閉じるボタンが押された時は自動的に閉じるので、このメソッドを呼び出す必要はありません。
