:Version: 4.0.1
:toc: macro
:toc-title: 目次
:toclevels: 4

= インタースティシャル（全画面）広告ガイド AMoAd SDK {version} Guide for Android

NOTE: インタースティシャル広告の概要については、link:Overview-Interstitial.asciidoc[こちら]をご参照ください。

NOTE: SDKのインストールについてはlink:Setup.asciidoc[こちら]をご参照ください。

NOTE: モジュールのダウンロードはこちら（link:https://github.com/amoad/amoad-android-sdk/releases/latest[安定版]/link:https://github.com/amoad/amoad-android-sdk/releases#[最新版]）からお願いします。

NOTE: サンプルコードが/Samples/Eclipse/AMoAdInterstitialSample/と + 
/Samples/AndroidStudio/AMoAdInterstitialSample/にありますので、管理画面から取得したsidを入力して動かしてください。

toc::[]

:numbered:
:sectnums:

== 広告を表示する

=== 実装の流れ

. 管理画面から発行されるsidを指定してモジュールを登録します。 +
`com.amoad.InterstitialAd.prepare(this, SID);`
. パネル画像を設定します。 +
`com.amoad.InterstitialAd.setPanel(SID, R.drawable.amoad_panel);`
. ボタン押下時など広告の表示を開始したいタイミングで、以下のメソッドを呼び出します。 +
```
com.amoad.InterstitialAd.show(SID, new com.amoad.InterstitialAd.OnCloseListener() {
		@Override
		public void onClose(com.amoad.InterstitialAd.Result result) {
    }
});
```

TIP: パネル以外の画像を標準画像から変える場合は、担当営業までお問合せください

=== 実装例

.MainActivity
[source,java]
----
public class MainActivity extends Activity {
  private static final String SID = "管理画面から発行されるsidを設定してください";
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    // インタースティシャル広告の準備
    com.amoad.InterstitialAd.prepare(this, SID);
    // 閉じるボタン画像（40dpx40dp）
    com.amoad.InterstitialAd.setCloseButton(SID, R.drawable.amoad_close_btn, R.drawable.amoad_close_btn_h);
    // リンクボタン画像（280dpx50dp）
    com.amoad.InterstitialAd.setLinkButton(SID, R.drawable.amoad_link_btn, R.drawable.amoad_link_btn_h);
    // パネル画像（310dpx380dp）
    com.amoad.InterstitialAd.setPanel(SID, R.drawable.amoad_panel);

    findViewById(R.id.show).setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View v) {
        // インタースティシャル広告を表示する
        com.amoad.InterstitialAd.show(SID, new com.amoad.InterstitialAd.OnCloseListener() {
          @Override
          public void onClose(com.amoad.InterstitialAd.Result result) {
            switch (result) {
            case Click:
              // リンクボタンがクリックされたので閉じました
              break;
            case Close:
              // 閉じるボタンがクリックされたので閉じました
              break;
            case CloseFromApp:
              // 広告のクローズ
              break;
            case Duplicated:
              // 既に開かれているので開きませんでした
              break;
            case Failure:
              // 広告の取得に失敗しました
              break;
            }
          }
        });
      }
    });
  }
}
----

== API詳細
=== InterstitialAdクラス
==== prepare関数
管理画面から発行されるsidに紐づく広告情報を登録します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|===

==== setPanel関数
パネル画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|resId |int 2+|パネルに使用する画像のリソースＩＤ
|===

==== setLinkButton関数
リンクボタン画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|resId |int 2+|リンクボタンに使用する画像のリソースＩＤ
|highlighted_resId |int 2+|リンクボタンに使用する画像（Highlight時）のリソースＩＤ
|===

==== setCloseButton関数
閉じるボタン画像を設定します。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|resId |int 2+|閉じるボタンに使用する画像のリソースＩＤ
|highlighted_resId |int 2+|閉じるボタンに使用する画像（Highlight時）のリソースＩＤ
|===

==== show関数
広告の表示を行います。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|===

==== close関数
広告を閉じます。
[options="header"]
|===
|パラメタ名 |Type 2+|Value
|sid |String 2+|管理画面から発行されるsidを設定してください
|===

TIP: リンクボタン、閉じるボタンが押された時は自動的に閉じるので、このメソッドを呼び出す必要はありません。
